### ISSUE TITLE
Div fence inside code block

### ISSUE THREAD

**Issue by hellux** [jgm/djot#109]
Divs can be closed by a verbatim fence inside a code block:

````markdown
::: outer

```
:::
```

:::
````

````html
<div class="outer">
<pre><code></code></pre>
</div>
<pre><code>
:::
</code></pre>
````

Is this intended? It is certainly easier to parse this way, not having to ignore fences inside code blocks.

An easy user workaround is to simply use a longer fence:

````markdown
:::: outer

```
:::
```

::::
````

````html
<div class="outer">
<pre><code>:::
</code></pre>
</div>
````

**Comment by jgm** [comment]
I don't think this was explicitly intended, and it seems an odd result!
I'm going to call it a bug, pending further thought and investigation.
