### ISSUE TITLE
Escaped pipes in tables

### ISSUE THREAD

**Issue by hellux** [jgm/djot#111]
The [syntax reference](https://github.com/jgm/djot/blob/510c92d6f23490eddee9b036c21b92190ea65ad7/doc/syntax.md?plain=1#L649) mentions that "Djot is smart enough to recognize backslash-escaped pipes and pipes in verbatim spans; these do not count as cell separators". It lists

```markdown
| just two \| `|` | cells in this table |
```

which [generates](https://github.com/jgm/djot/blob/510c92d6f23490eddee9b036c21b92190ea65ad7/doc/syntax.html#L1516)

```html
<table>
<tr>
<td>just two \</td>
<td><code>|</code></td>
<td>cells in this table</td>
</tr>
</table>
```

It has separated into three cells and shows the backslash, but I am assuming it is supposed to be:

```html
<table>
<tr>
<td>just two | <code>|</code></td>
<td>cells in this table</td>
</tr>
</table>
```

**Comment by jgm** [comment]
Thanks, added a test for this.
Will fix later.
