### ISSUE TITLE
{_ opener can match with bare _

### ISSUE THREAD

**Issue by matklad** [jgm/djot#119]
```
{_ x_ _}
```

This is somewhat counter-intuitively parsed as `<em> x</em> _}`, not as `<em> x_ </em>`

**Comment by jgm** [comment]
This is actually according to spec.

> In cases of ambiguity, `{` and `}` may be used to mark delimiters as openers or closers. Thus `{_` behaves like `_` but can only open emphasis, while `_}` behaves like `_` but can only close emphasis:

Nothing here says that `{_` must pair with `_}`; it can be closed by any `_` which can close emphasis.

I agree, though, that visually you'd expect something else here.

I'd have to think about what would be required to add the rule that an explicit `{x` marker can only be closed by an explicit `x}`.
