### ISSUE TITLE
What's the proper way to generate three endash in a row?

### ISSUE THREAD

**Issue by crlf0710** [jgm/djot#120]
Seems six `-`s will be recognized as two emdash in a row, which is ok by itself. However, i wonder for a `djot`-writer, what's the proper way to write `djot` if three endash is instead what one's intended output?

**Comment by jgm** [comment]
This would work but it's awkward:
```
--{%%}--{%%}--
```
(empty comments to separate)

Or, just use unicode en-dashes.

**Comment by crlf0710** [comment]
@jgm Please consider revisit this after #112 is resolved... I'd say something like allowing user to write `:endash::endash::endash:` for this purpose is cleaner from the ast perspective.
