### ISSUE TITLE
Prettier plugin or standalone formatter

### ISSUE THREAD

**Issue by mtsknn** [jgm/djot#129]
Not sure if this is in the scope of this project/repo, but here goes:

Prettier is essential for me when authoring Markdown, so I'd very much like a Djot formatter. Maybe not yet, considering that Djot is still evolving, but eventually.

Benefits:

- Consistently formatted Djot files
- More readable Djot files
- Could also work as a "syntax checker" for code blocks
  - Prettier is very good at formatting Markdown because it also formats code blocks (naturally only languages that Prettier supports). Formatting code blocks brings nice and consistent formatting but also works as a syntax checker: if Prettier doesn't format a code block, I know that the code must have a syntax error.

Some things to format off the top of my head:

- Adjust indentation
- Add missing `>`'s to quote blocks
- Remove consecutive spaces between words
- Remove consecutive blank lines
- Remove trailing whitespace (though most editors can also be configured to do this)
- Format code blocks
  - It could be nice if one could configure what code formatters the Djot formatter should use. E.g. Go code blocks could be configured to be formatted with gofmt, and JavaScript code blocks with Prettier _or_ `deno fmt`. This would be better than Prettier + Markdown as Prettier supports only a few languages.
- Align table columns
- [More ideas in the Prettier repo](https://github.com/prettier/prettier/tree/main/tests/format/markdown) (I just found this so I haven't taken a closer look yet)

Example:

- Before:

  ````md
  1.  This is   a
  list item.

  > This is a block
  quote.


  ```js
  const
   foo  =
  'bar' ;
  ```
  ````

- After:
  ````md
  1. This is a
     list item.
  
  > This is a block
  > quote.
  
  ```js
  const foo = 'bar'
  ```
  ````

**Comment by jgm** [comment]
If you have pandoc, you can already do this kind of reformatting by using the custom lua reader/writer supplied in this repository.

````
$ pandoc -f djot-reader.lua -t djot-writer.lua
1.  This is   a
list item.

> This is a block
quote.


```js
const
 foo  =
'bar' ;
```
````
Result:
````
1. This is a list item.

> This is a block quote.

``` js
const
 foo  =
'bar' ;
```
````

Note: you defiintely don't want line breaks to be changed in a code block, as in your example, since that changes the semantics.

**Comment by jgm** [comment]
That said, it would be nice to have a native djot renderer built in.

**Comment by jgm** [comment]
Oh I see, I suppose the prettier formatter will pass javascript code through a javascript code formatter?
Well, that can certainly be done with djot using filters. More documentation on that coming later.

**Comment by mtsknn** [comment]
> If you have pandoc, you can already do this kind of reformatting by using the custom lua reader/writer supplied in this repository.

Nice. Is there a way to preserve line breaks (in prose)? I like [Semantic Line Breaks](https://sembr.org/), but the example you provided breaks that.

> Oh I see, I suppose the prettier formatter will pass javascript code through a javascript code formatter?

Exactly. Looks like I failed to articulate that.

> Well, that can certainly be done with djot using filters. More documentation on that coming later.

Nice. I'll repeat one point from my previous comment now that we are on the same page regarding code formatting:

> It could be nice if one could configure what code formatters the Djot formatter should use. E.g. Go code blocks could be configured to be formatted with gofmt, and JavaScript code blocks with Prettier _or_ `deno fmt`. This would be better than Prettier + Markdown as Prettier supports only a few languages.

**Comment by waldyrious** [comment]
> Nice. Is there a way to preserve line breaks (in prose)?

I suppose #108 (i.e. supporting  a concrete syntax tree) might be able to address this use case.

**Comment by jgm** [comment]
Closing this in favor of #135
