### ISSUE TITLE
Playground seems to fail with list examples

### ISSUE THREAD

**Issue by eugenesvk** [jgm/djot#139]
Pasted the example from the docs
```
- one

  - two
  - three
```
and got nothing
<img width="956" alt="pg" src="https://user-images.githubusercontent.com/12956286/203511839-c53cd6be-6f5d-491f-8869-c723719d36db.png">

**Comment by jgm** [comment]
Hm, that's odd.  Looks like it renders as soon as you add some non-list content below the list.

This just uses the C library, compiled to WASM by emscripten.
The C lib doesn't do this by itself.

**Comment by jgm** [comment]
Actually this issue does show itself if you run with the `-p` option for source positions (this is enabled by default on the playground but the tests don't yet test it).
