### ISSUE TITLE
Clarify whitespace before and after language specifier

### ISSUE THREAD

**Issue by MarkLodato** [jgm/djot#154]
The [spec](https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#code-block) currently reads (emphasis added):

> A code block starts with a line of three or more consecutive backticks, **optionally followed by whitespace and a language specifier, but nothing else.**

This incorrectly implies:

- That whitespace is required before the language specifier.
- That whitespace is disallowed after the language specifier.

I was confused because this would be difference from GitHub Flavored Markdown and was wondering the rationale behind the change. When I tried it in the playground, I saw that whitespace around the language specifier is ignored.

I suggest something like:

> A code block starts with a line of three or more consecutive backticks, **optionally followed a language specifier, but nothing else. The language specifier may optionally be preceded and/or followed by whitespace.**

I'm happy to send a PR if you agree.

**Comment by jgm** [comment]
Sounds good to me. If you do a PR, do `make doc/syntax.html` to compile the HTML version.
