### ISSUE TITLE
Pipe table should clarify that one separator row is conventional

### ISSUE THREAD

**Issue by MarkLodato** [jgm/djot#155]
The [spec](https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#pipe-table) does not explicitly say that the convention is for a single separator row. The very first example shows a separator between every row:

```
| a  |  b |
|----|:--:|
| 1  | 2  |
|:---|---:|
| 3  | 4  |
```

This implies that a separator is required between each row. Nothing explicitly states that separators are not required, and no examples shows multiple rows without separators between.

I think it would be helpful to start with a more conventional example, something like:

```
| decimal | alpha |
| --- | --- |
| 1 | a |
| 2 | b |
| 3 | c |
```

**Comment by jgm** [comment]
Actually, that example is meant to show a case with two heading rows.  A row with a separator under it is a heading.
But perhaps you're right that a simpler example up front is a good idea.

**Comment by jgm** [comment]
@waldyrious no, I prefer the current approach.
