### ISSUE TITLE
Comments can break task lists

### ISSUE THREAD

**Issue by tbdalgaard** [jgm/djot#186]
Reproduced this in the playground:
https://djot.net/playground/?text=List+with+comments%3A%0A%0A-+%5Bx%5D+This+is+my+first+task+today.%0A%7B%25+It+was+actually+quite+easy+to+complete.%25%7D%0A-+%5B+%5D+This+is+my+second+task+for+today.%0A%7B%25+That+is+not+as+easy+as+the+first+task+I+finished+today.%25%7D%0A-+%5B+%5D+This+is+the+third+and+final+task.%0A%7B%25+That+will+be+completed+after+lunch.%25%7D%0A%0AEnd+of+tasks+%3A%29

The issue is that if I want to make comments on a newline after the task list item this splits the task list into three different task lists.
I find it easier to read when I can start the comment on a newline.

Is this expected behaviour, or how could I get one list with three tasks and the internal comments?

**Comment by jgm** [comment]
Yes, it's expected.  An attribute (or comment) at the left margin will interrupt a list item. If you don't want this, put the attribute (comment) inside the list item, using indentation, [like this](<https://djot.net/playground/?text=List+with+comments%3A%0A%0A-+%5Bx%5D+This+is+my+first+task+today.%0A++%7B%25+It+was+actually+quite+easy+to+complete.%25%7D%0A-+%5B+%5D+This+is+my+second+task+for+today.%0A++%7B%25+That+is+not+as+easy+as+the+first+task+I+finished+today.%25%7D%0A-+%5B+%5D+This+is+the+third+and+final+task.%0A++%7B%25+That+will+be+completed+after+lunch.%25%7D%0A%0AEnd+of+tasks+%3A%29>)

**Comment by tbdalgaard** [comment]
Great, totally forgot about this. Thanks!
