### ISSUE TITLE
[suggestion] unless rationale rule 11, I suggest some alternative element syntax make djot more useable

### ISSUE THREAD

**Issue by ffel** [jgm/djot#187]
I suspect (and I hope) djot will become a perfect format to write plain text texts.

I think usability will increase if (like in pandoc) some elements can be typed in "lazy mode" which can be formatted into "proper formatted text" later on.

As an illustration my workfow with pandoc with _footnotes_: I typically start typing these in "lazy mode" `^[like this being the first few words in my footnote]`. Next, I format the footnotes with `pandoc`, which adds a correct footnote number, bootstraps the footnote in final format after which it is easy for me to complete the footnote, e.g. by adding more paragraphs to the footnote.

I suspect there are more pandoc "lazy formatting mode" elements which are quicker to type than in the eventual format (tables come to my minde).

(to be clear: I'm pretty fond of pandoc formatting plain text. Moreover, I am especially happy that I can type text quicker and trust in pandoc to make my texts well formatted plain text)

**Comment by jgm** [comment]
What you're talking about is a reformatting tool.  This isn't a syntax issue.

You can reformat already using djot.js: `djot -t jdot`.
