### ISSUE TITLE
List of attributes in Djot

### ISSUE THREAD

**Issue by tbdalgaard** [jgm/djot#188]
Is there a place to look for all legal and possible attributes that will work in Djot?

I see some examples in the documentation, and want to know where those came from. Do we need to specify every attribute ourselves or are there some predefined attributes?
For example there are attributes for setting languages, collars etc. but how would a new user explore available attributes?

**Comment by jgm** [comment]
There are no predefined attributes. How attributes are handled is renderer-specific. The HTML renderer just passes them through as attributes of the element.  Filters can do what they like with them.

**Comment by tbdalgaard** [comment]
Ok, so attributes like caps, lang etc. is specific for the format which Djot converts to, and that's the reason?
So one can research LATEX, HTML etc. and find which attributes is legal syntax and use them as wanted in the Djot source document?

If the above is true, then it is very very interesting.

Sendt fra min Mac Mini via Apple Mail
