### ISSUE TITLE
Heading attribute is not set inline for headings

### ISSUE THREAD

**Issue by tbdalgaard** [jgm/djot#23]
When converting from Markdown to Djot I see that attributes for headings are placed on a blank line before the heading. As I understand the syntax attributes for inline can be at the end of the line like.

```
# Heading {#top}

```

Djot gives the following output when I convert the sample above:

```
{#top}
# Heading

```

This was found when experimenting with the filter via Pandoc.

**Comment by jgm** [comment]
Yes, that's how attributes are done in djot. They are placed on a line before the block they modify.

**Comment by jgm** [comment]
https://djot.net/playground/syntax.html#block-attributes

**Comment by tbdalgaard** [comment]
Ok, I just thought a heading could be seen as a inline element, and that the syntax from Comonmark could be used here as valid syntax.
I understand why the structure and syntax is that way, I just like to read the text and then an identifier at the end of the block rather than at the lied above the content.

**Comment by jgm** [comment]
No worries. Headings are block-level elements.  Inline elements are things that could go inside a paragraph.
