### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN for djot.net

### ISSUE THREAD

**Issue by noughtmare** [jgm/djot#256]
I have to add a security exception to be able to visit djot.net.

**Comment by jgm** [comment]
That's odd, I haven't experienced that, and my browser says the certificate is valid. Is anyone else having difficulties of this kind?

**Comment by noughtmare** [comment]
It seems to work fine for me now too, but yesterday it didn't. See discussion here: https://kbin.social/m/haskell/t/626080/Haskell-Interlude-Episode-37-John-MacFarlane#entry-comment-3565604

**Comment by noughtmare** [comment]
Oh, for some reason I wrote www.djot.net, that must have been the problem.
