### ISSUE TITLE
Two asterisks for “strong”?

### ISSUE THREAD

**Issue by rauschma** [jgm/djot#285]
Djot could use two asterisks for strong:

* Upside: backward compatibility with Markdown. The single-asterisk strong formatting is one of the few frequently used djot syntaxes that’s not backward compatible.
* Downside: more verbose. In my Markdown documents, I always use `_` for emphasis and `**` for strong and I never particularly liked the clutter caused by the latter.

**Comment by jgm** [comment]
No.  See my article "Beyond Markdown" and the README.md.

**Comment by rauschma** [comment]
Sure!

(I did read the readme. Double asterisks per se did not make parsing complicated in CommonMark – it was allowing both single and double asterisks.)

**Comment by jgm** [comment]
Ah, I see. Just double asterisks.  Well, that is another choice that could have been made.
