### ISSUE TITLE
Suggested principle: Invisible whitespace is never significant

### ISSUE THREAD

**Issue by vassudanagunta** [jgm/djot#3]
Djot's treatment  of hard line breaks violates this principle. In djot, this:
```
I can write it on the door   \
I can put it on the floor   \
I can do anything that you want me for   \
If you want me to   \
```
nicely renders as:

> I can write it on the door  
> I can put it on the floor  
> I can do anything that you want me for  
> If you want me to  

But this:
```
Do it right, do it wrong    \ 
'Cause a matter of fact, it'll turn out to be strong    \
If you want me to    \
```

renders as 

> Do it right, do it wrong 'Cause a matter of fact, it'll turn out to be strong  
> If you want me to  

because there happens to be an accidental trailing space on the first line.

## Suggested principle: Invisible whitespace is never significant

I think in a human oriented plain text format, invisible or non-obvious whitespace should have no significance. By "invisible", I mean not obviously present to the human eye. That there is a space between words is obvious, but not how many spaces, or that there are spaces at the end of a line, or the *number* of spaces at the beginning of a line (when a non-fixed width font is used).

I think djot gets it right in this regard with one exception I've found so far (above). For example, I like that djot doesn't have a magic indent threshold like Markdown's 4 spaces: the transition from 3 to 4 results in dramatically different output, and the transition from 4 to 5 spaces results in subtly but significantly different output.  Likewise one doesn't have to count spaces to make sure that successive lines of a list item are treated as such. In fact the interaction between Commonmark's four spaces code block and the space to signify list item continuation results in very unintuitive behavior.

**Comment by jgm** [comment]
I think this is a good suggestion.

**Comment by jgm** [comment]
There are pros and cons here.  The case against this is that it adds complexity to the rules.  Instead of saying that backslash + space is always a nonbreaking space, we need to qualify that, since backslash + a space followed by tabs and newline would be a hard break.

**Comment by jgm** [comment]
Another option would be to remove the 'backslash + newline = hardbreak' rule and add something like pandoc's line blocks for the rare cases when intra-paragraph line breaks are needed.

**Comment by vassudanagunta** [comment]
> Instead of saying that backslash + space is always a nonbreaking space, we need to qualify that

I can't think of a use case for non-breaking spaces at the end of a line, except perhaps as a hack to widen a column of text, e.g. in a table cell.  So it wouldn't be a qualification that anyone needs to learn or remember. A purely technical detail that can be in a tiny footnote.

The user-friendly syntax description can simply say that all trailing spaces are ignored, and not worry about explaining that it means non-breaking spaces at the end of a line aren't supported.

**Comment by vassudanagunta** [comment]
> Another option would be to remove the 'backslash + newline = hardbreak' rule and add something like pandoc's line blocks for the rare cases when intra-paragraph line breaks are needed.

I personally much prefer

```
I can write it on the door   \
I can put it on the floor   \
I can do anything that you want me for   \
If you want me to   \
```

to 

```
| I can write it on the door 
| I can put it on the floor 
| I can do anything that you want me for  
| If you want me to
```

Perhaps coincidentally, or perhaps not, slashes are a standard way to delimit lines of poetry, though it's forward not backslashes, and in place of not along with line breaks. Still, that standard, I think, makes the backslash line endings feel natural.

[Quoting Poetry | Kent State University](https://www.kent.edu/writingcommons/quoting-poetry):

> The format of poetry quotations informs the reader in a nonverbal way that the quoted passage is from a poem, not a prose piece. Essentially, the two formats differ to improve the clarity and ease of reading an essay.
>
> Place a forward slash (/) between  each quoted line

From the MLA Handbook, on quoting two or three lines of verse:

> Follow the rule for quoting one line, and use a forward slash with a space on each side ( / ) to indicate where the line breaks fall

It's even [aesthetically pleasing for some](https://daysibley.wordpress.com/2016/03/02/forward-slash-in-a-poem/):
> In my newer poems, I have been using forward slashes a lot, instead of commas. I made this choice because I enjoy how forward slashes look visually and because they can function as new punctuation for me. They do not only divide text according to breath or idea but also poetic impulse. My newer works are filled with forward slashes that continuously flip and chop the image or tone of a poem. The forward slashes serve to create a sense of speed or chaos. For me, they resemble the blast beats made by drummers in punk bands. The forward slashes look like drum sticks, charging energy throughout the poem. The punctuation in my poems mimic the energy of punk shit.
~ Christopher Soto, I Have Punk, Langston Had Blues, Lorca Had Gypsy Ballads


For some poetry *all* whitespace is significant. For example [John Donne's *A Valediction: of Weeping*](https://www.poetryfoundation.org/poems/44132/a-valediction-of-weeping):

```
        Let me pour forth
My tears before thy face, whilst I stay here,
For thy face coins them, and thy stamp they bear,
And by this mintage they are something worth,
         For thus they be
         Pregnant of thee;
Fruits of much grief they are, emblems of more,
When a tear falls, that thou falls which it bore,
So thou and I are nothing then, when on a diverse shore.

         On a round ball
A workman that hath copies by, can lay
An Europe, Afric, and an Asia,
And quickly make that, which was nothing, all;
         So doth each tear
         Which thee doth wear,
A globe, yea world, by that impression grow,
Till thy tears mix'd with mine do overflow
This world; by waters sent from thee, my heaven dissolved so.
```

While Pandoc's approach supports that, if i remember correctly, preceding each line with a `|` I think undermines if not spoils the visual intent:

```
|         O more than moon,
| Draw not up seas to drown me in thy sphere,
| Weep me not dead, in thine arms, but forbear
| To teach the sea what it may do too soon;
|         Let not the wind
|         Example find,
| To do me more harm than it purposeth;
| Since thou and I sigh one another's breath,
| Whoe'er sighs most is cruellest, and hastes the other's death.
```

Just using a code block is better than polluting the verse with special formatting indicators.

**Comment by jgm** [comment]
Note also that currenty djot inserts (presumably unwanted) spaces before the hard breaks in
```
I can write it on the door   \
I can put it on the floor   \
I can do anything that you want me for   \
```
To avoid these you'd need `\` to come right after the last letter in each line.

So, one proposal would be that `SPACES? BACKSLASH SPACES? NEWLINE` is a hard break.
