### ISSUE TITLE
Request document about multiple line block attributes

### ISSUE THREAD

**Issue by black-desk** [jgm/djot#330]
Djot syntax reference says:

> Block attributes have the same syntax as inline attributes, but they must fit on one line.

But in djot.js test:

https://github.com/jgm/djot.js/blob/a50487c727e0d36a5d82636f773519e575d733e5/test/attributes.test#L112-L119

Should we update syntax reference?

**Comment by jgm** [comment]
Actually, the version in the repository says:

> Block attributes have the same syntax
as inline attributes, but if they don't fit on one line, subsequent lines
must be indented.

Commit b96386c139038c00ff3908c9c9e64a6d677e9315

I guess we just need to update the website.
