### ISSUE TITLE
A note on having more "smart" typography?

### ISSUE THREAD

**Issue by Omikhleia** [jgm/djot#332]
Djot has a fairly good support for smart punctuation, but the latter is restricted to interpreting, based on context, straight double quotes and single quotes -- e.g. for them to be replaced by appropriate typographical quote marks[^1] or apostrophes.

There could be more "smart" uses case, however, that could be interesting conveniences for the typists...
 - 51° 45' 07" is clearly a latitude or longitude and could be parsed and rendered so as to become 51° 45′ 07″ (with prime symbols)
 - Catalan paral·lel (with _punt volat_); or, say, "gender-inclusive" French associé·e (for another example of middle dot, whatever one things about it) would be easier to enter as paral.lel and associé.es (as some people do in e-mail, etc.); and, well any language using the interpunct for some reason...
 - And perhaps other interesting cases?[^2]

Of course, one way to look at this is that users can configure they input devices or editors to make such characters more easily available.

But why having smart punctuation at all then, in the first place?
The other way round, shouldn't Djot have more "smart" stuff built-in?

[^1]: E.g. by default, in "naive" renderers, curly quotes -- but in more advanced renderers, to appropriate language-dependent quote marks.

[^2]: Sequence numbers vs. Durations are another direction worth mentioning, although not that straightforward to handle at syntax level, and a span here is probably easier anyway.

**Comment by jgm** [comment]
I'm not in favor of getting that smart.  This kind of smartness tends to get triggered in cases where it isn't intended (or anticipated).  For these specialized uses, it's easy enough to enter the right character in the first place.

**Comment by Omikhleia** [comment]
Well understood.
Yet:
> This kind of smartness tends to get triggered in cases where it isn't intended (or anticipated)

Do you have literature examples, where a period between letters might be a real period?

**Comment by jgm** [comment]
> Do you have literature examples, where a period between letters might be a real period?

e.g., `e.g.`.
e.g., `Filename.txt`.
e.g. `F.B.I.`
e.g., `M.Eng`
