### ISSUE TITLE
error when parsing empty table cells 

### ISSUE THREAD

**Issue by FrankFischer** [jgm/djot#55]
"| a |" (without the quotes) produces a one cell table.
If you delete just the letter "a" then 
https://djot.net/playground/ hangs and has to be reloaded
(caused by "ast.lua:520: unmatched -row encountered at byte xxxx").

A workaround is  "| \ |" (which puts a non breaking space into the cell).
But this looks a little bit clumsy.

**Comment by jgm** [comment]
Thanks. Looks like `cell` is open but  not closed:
```
% lua bin/main.lua -m
| |
+table 1-1
+row 1-1
+cell 1-1
-row 3-3
-table 5-5
```
