### ISSUE TITLE
Consider adding "AST in JSON" output fromat

### ISSUE THREAD

**Issue by matklad** [jgm/djot#58]
Problem: I'd love to experiment with djot, but I don't know lua, and would rather use a language I am already familiar with (Rust or TypeScript). 

Proposed solution: add `djot -a -j`  to output AST in some JSON format which then could be easily consumed by other programs. 

I *think* I probably can get something like this via `pandoc`, but I'd rather avoid adding one more tool to the pipeline. 

Yeah, the appropriate pandoc spell is `pandoc -f djot-reader.lua -t json example.djot`. There's another drawback with that approach: today's pandoc `json` output is a rather low-level encoding of Haskell data structures, it's not something you can just `JSON.parse` in javascript and get a _natural_ API. I think there's some benefit to defining a more first-class JSON AST encoding for djot.

**Comment by matklad** [comment]
Yeah, I don't think a library is required to *emit* json, we can just push stuff to string, the same what we do for HTML (I think?)

Very much appreciate the zero-dependency nature of the reference impl!

**Comment by matklad** [comment]
I think this is mostly done now, via `-a -j`. Most of discussion here happened in #60 :)

**Comment by jgm** [comment]
I've added this to the live sandbox, too
