### ISSUE TITLE
div blocks don't allow underscores in class names

### ISSUE THREAD

**Issue by matklad** [jgm/djot#64]
```djot
[inline]{.a_b_c}

::: a_b_c

:::
```

I'd  expect both `a_b_c` to parse as a class name. The second one doesn't: 

```
doc
  para
    span class="a_b_c"
      str s="inline"
  para
    str s="::: a"
    emph
      str s="b"
    str s="c"
  div
references = {
}
footnotes = {
}
```

**Comment by matklad** [comment]
And the second problem is English bias (which I think is OK for attributes, but still):

```
::: блок
:::
```

It seems reasonable to just allow anything between whitespace perhaps?

**Comment by bpj** [comment]
Not English bias but ASCII/byte string bias, and its a limitation of Lua patterns so unavoidable in a Lua implementation if you want to avoid some hefty C dependency.
