### ISSUE TITLE
Do we need syntax for many styles of ordered lists?

### ISSUE THREAD

**Issue by matklad** [jgm/djot#70]
I don't have a strong opinion at the moment, but these two observations seem curious: 

* we have a lot of various syntaxes for various types of markers of ordered lists: https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#list-item
* it seems that in reality there many more possibilities: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

Which makes me wonder -- perhaps we shouldn't try to cover all variations syntactically, and instead leave it to styling? 

Eg,

```
{style="list-style-type: upper-roman"}
1. one
2. two
3. thee
```

(and of course it's possible to define a standard class `{.upper-roman}`)

To distill this:

* it feels suboptimal that our syntax covers only part of the design space
* it feels a bit like a layering violation -- this is a styling concern, not document structure concern.

**Comment by jgm** [comment]
We're still basically motivated by the Markdown philosophy of trying to make the source documents readable as they are -- they should read like documents, not code.  So, this is much better from that point of view:
```
I.  one
II.  two
III.  three
```

**Comment by matklad** [comment]
uhu. I think it's useful to tease that apart into two somewhat orthogonal bits:

- _readable_ in the source form (source readability)
- source form visually resembles rendered from (wysiwyg)

I would say that `1` vs `i` score about the same on the source readability, but `i` is a clear win on the wysiwyg. 

Couple of other cases where this oppositions comes up: 

- hard-wrapping is wysiwyg, but "sentence per line" is raw readability/diffability 
- pipe tables is wysiwyg, but  "cell per line" is raw readability 

---

I personally care more about raw readability, than wysiwyg (I author complex documents with a fair amount of custom stuff, so I have an inherent wysiwyg gap). 

I think the reasonable stance is to make wysiwyg syntax just work via extra formatting (eg, if you reformat a "cell-per-line" table into "row-per-line", you get wysiwyg). Which means, yeah, we should support `i`, `ii`, `iii` syntax, but maybe pandoc's `#.` / asciidoctor's `.` as well. 

It _is_ unfortunate that we don't support every list style out there, but that is justified by our "no Unicode classes" rule for the parser. 

Convinced myself that the answer here is yes, thanks :-)

**Comment by jgm** [comment]
I'm open to supporting something like `#.`.
