### ISSUE TITLE
Fork the playground or include it as a submodule

### ISSUE THREAD

**Issue by waldyrious** [jgm/djot#72]
The original [playground repository](https://github.com/dtinth/djot-playground) is marked as not maintained. There are changes that should be done to it (for example, there's a bug with handling triple-backtick code blocks), so the code should either be forked to a separate repository, or included in this one as a git submodule, so that it can receive bugfixes and improvements (which may be pushed back upstream if the maintainer decides to accept them).

**Comment by jgm** [comment]
Oh, the playground I'm using on djot.net is already a fork.
https://github.com/jgm/djot-playground

**Comment by waldyrious** [comment]
Oh, cool, I hadn't notice that. I've opened https://github.com/jgm/djot-playground/issues/4 to track the code block issue mentioned above.
