### ISSUE TITLE
Use [] instead of {} to wrap inline markup

### ISSUE THREAD

**Issue by waldyrious** [jgm/djot#73]
Using `[_foobar_]` instead of `{_foobar_}` would be more consistent with the other uses of `{...}` referring to non-text content (attributes), and with content inside `[...]` denoting the textual part of elements (chiefly, `[links]()`).

Prior art: This `[]`-based syntax has already been tested in the wild with Textile (e.g. see [docs for bold/strong](https://textile-lang.com/doc/strong-and-bold-text)), and I'm not aware of issues found by Textile authors derived from that choice of characters.

**Comment by jgm** [comment]
The problem with this is that `[..]` is already dedicated to links and spans.
