### ISSUE TITLE
Implement scroll-sync in playground

### ISSUE THREAD

**Issue by jgm** [jgm/djot#84]
We can copy what commonmark.js's dingus does.

**Comment by jgm** [comment]
Implemented left->right sync.
Would also be good to have right->left sync.

**Comment by jgm** [comment]
Right, I just noticed these odd differences.

When I paste a document in, Safari puts in two blank lines for every one.
Firefox collapses all of them.
Chrome looks right.

**Comment by jgm** [comment]
The weird behavior seems linked to my adding the `whitespace-nowrap` tailwind class.
But I *don't* want auto-wrapping because it defeats the scrollsync calculations.

**Comment by jgm** [comment]
It's fixed now, I think.

**Comment by waldyrious** [comment]
> It's fixed now, I think.

Not quite, I'm afraid :(

Here's what I see in Firefox:

![image](https://user-images.githubusercontent.com/478237/201516428-fa0608c8-d550-4a0a-8062-6c338020f508.png)

And in Brave:

![image](https://user-images.githubusercontent.com/478237/201516464-daf5b9b8-1b75-4af9-9d17-238f6226fa02.png)

**Comment by jgm** [comment]
Sorry, what's the problem you see there?  There are slight differences in rendering, but the lines on the left look right.

**Comment by waldyrious** [comment]
Apologies, I assumed it would be more evident. The issue is the rendered content being cut off at around 182px of height (note the scrollbars).

It seems that this is due to the div wrapping the iframe not having `height:100%`, so it settles on the default iframe height (150px) plus the 1rem padding. The iframe then gets 100% of the available (182px) height.

**Comment by jgm** [comment]
OK, thanks.
Try it now.

**Comment by waldyrious** [comment]
Looks better indeed. But the `<pre id="result">` is shown under the `<iframe>` with a non-zero height (it seems to be roughly the same size as the iframe), which makes scrolling around in the page a little awkward. Shouldn't it be set to `display:none` if the output selection is set to "Preview"?

**Comment by jgm** [comment]
Done.
