### ISSUE TITLE
Change link to playground source

### ISSUE THREAD

**Issue by waldyrious** [jgm/djot#85]
The playground at https://djot.net/playground/ currently points to https://github.com/jgm/djot-playground, but since the code behind it has been [replaced](https://github.com/jgm/djot/issues/60#issuecomment-1309240569), it should instead point to https://github.com/jgm/djot/tree/main/clib/web (which might benefit from a README, btw).

Also, the README and website field of https://github.com/jgm/djot-playground should probably be updated as well to avoid giving people the wrong idea.

**Comment by jgm** [comment]
Done.
