### ISSUE TITLE
Syntax reference: no mention of tilde for code block fence

### ISSUE THREAD

**Issue by hellux** [jgm/djot#90]
The [syntax reference](https://github.com/jgm/djot/blob/388a2e8d85b98cc32ff0894d85b6eddea5716bb1/doc/syntax.md?plain=1#L533) says a code block may start with a fence of 3 or more backticks. However, the [implementation](https://github.com/jgm/djot/blob/388a2e8d85b98cc32ff0894d85b6eddea5716bb1/djot/block.lua#L446) allows tildes to be used as well, which is not mentioned in the reference.

**Comment by matklad** [comment]
I think this might be a dupe of https://github.com/jgm/djot/issues/41.

My TL;DR: we indeed support both, it's not clear whether we should though. backtick is standard, but tilda looks nicer, but backtick is easier to type.

**Comment by hellux** [comment]
Ah, yes, seems to be a duplicate, forgot to make a search first.
