### ISSUE TITLE
# in heading generates more headings

### ISSUE THREAD

**Issue by hellux** [jgm/djot#91]
The [syntax reference](https://github.com/jgm/djot/blob/4114418151201310f89a670a21bee1e55b69f691/doc/syntax.md?plain=1#L371) states that a heading is a sequence of `#` characters followed by whitespace followed by inline content. So I would expect
```markdown
# # a
```
to result in a heading "# a" but instead it results in 2 headings "" and "a".
```
+heading 1-1
-heading 1-1
+heading 3-3
str 5-5
-heading 5-5
```

Also for multi-line headings, the reference states that they end with a blank line or an enclosed container, so I would expect
```markdown
# a
# b
```
to result in a single heading "a # b" but instead it results in two headings:
```
+heading 1-1
str 3-3
-heading 3-3
+heading 5-5
str 7-7
-heading 7-7
```

**Comment by jgm** [comment]
Yeah - that's weird and not intended!
Will need to look into it.

**Comment by jgm** [comment]
On your second question, multiline headings would look like this:
```
# This is a
multi-line heading

Here is the paragraph.
```
Or you could indent:
```
# This is a
  multi-line heading
```

**Comment by hellux** [comment]
Actually, I was wondering if it was intended to allow a heading on the line immediately after another heading. From the wording in the syntax reference, it sounds like there must be a blank line between two headings, otherwise it will become a single multiline heading.

**Comment by jgm** [comment]
It was intended to allow this, but I agree it's not clear from the syntax doc.

I'm open to persuasion though about this.  Maybe it would be better to make
```
# a
# b
```
a multiline heading with content `a b`?

**Comment by jgm** [comment]
Reopening since at least I think we want to rewrite the syntax doc.

**Comment by hellux** [comment]
> It was intended to allow this, but I agree it's not clear from the syntax doc.
> 
> I'm open to persuasion though about this. Maybe it would be better to make
> 
> ```
> # a
> # b
> ```
> 
> a multiline heading with content `a b`?

Yeah, this seems more useful to me, and also quite intuitive.

More generally, I think I prefer requiring a blank line after any block for simpler parsing  / syntax description and better readability.

**Comment by kmaasrud** [comment]
> Maybe it would be better to make
> 
> ```
> # a
> # b
> ```
> 
> a multiline heading with content `a b`?

+1 on this.
